repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-added-large-files
- repo: https://github.com/hmcts/cpp-hooks-pre-commit-terraform
  rev: eb20c9cc3f11b1f60698fa3ce9ed32f19c603ca2
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-merge-conflict
- repo: https://github.com/hmcts/cpp-hooks-gitleaks
  rev: 8674df8b3bc84211bf951057daf23b081f5ca56a
  hooks:
    - id: gitleaks