name: CPP Terraform Azure Policy Management
trigger:
  branches:
    include:
    - master
pr:
- master

resources:
  repositories:
  - repository: cppAzureDevOpsTemplates
    type: github
    name: hmcts/cpp-azure-devops-templates
    ref: 'DTSPO-26989-flexible-stages'
    endpoint: 'hmcts'

parameters:
  - name: tfversion
    default: 1.12.2

stages:
  - stage: precommit
    pool:
      name: MDV-ADO-AGENTS-01
    jobs:
      - job: pre
        condition: eq(variables['Build.Reason'], 'PullRequest')
        steps:
          - template: steps/terraform/terraform-precommit.yaml@cppAzureDevOpsTemplates
            parameters:
              tfversion: ${{ parameters.tfversion }}

  # Plan Nonlive
  - template: stages/terraform-ws-plan.yaml@cppAzureDevOpsTemplates
    parameters:
      agentPool: MDV-ADO-AGENTS-01
      tfversion: ${{ parameters.tfversion }}
      azureServiceConnection: ado_nonlive_workload_identity
      vaultAdminCredentialsVarGroup: cpp-nonlive-vault-admin
      platform: nonlive
      environment: NLV
      tfvars: null
      stageName: plan_nlv
      serviceName: azure-policy
      targetResources: null

  # Plan Live
  - template: stages/terraform-ws-plan.yaml@cppAzureDevOpsTemplates
    parameters:
      agentPool: MPD-ADO-AGENTS-01
      tfversion: ${{ parameters.tfversion }}
      azureServiceConnection: ado_live_workload_identity
      vaultAdminCredentialsVarGroup: cpp-live-vault-admin
      platform: live
      environment: LVE
      tfvars: null
      stageName: plan_lve
      serviceName: azure-policy
      targetResources: null

  # Apply Nonlive
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    - template: stages/terraform-ws-apply.yaml@cppAzureDevOpsTemplates
      parameters:
        agentPool: MDV-ADO-AGENTS-01
        tfversion: ${{ parameters.tfversion }}
        azureServiceConnection: ado_nonlive_workload_identity
        vaultAdminCredentialsVarGroup: cpp-nonlive-vault-admin
        platform: nonlive
        environment: NLV
        tfvars: null
        stageName: apply_nlv

  # Apply Live
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    - template: stages/terraform-ws-apply.yaml@cppAzureDevOpsTemplates
      parameters:
        agentPool: MPD-ADO-AGENTS-01
        tfversion: ${{ parameters.tfversion }}
        azureServiceConnection: ado_live_workload_identity
        vaultAdminCredentialsVarGroup: cpp-live-vault-admin
        platform: live
        environment: LVE
        tfvars: null
        stageName: apply_lve

  # Trigger compliance scan
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    - stage: trigger_scan
      displayName: Trigger Policy State Scan
      dependsOn:
        - apply_nlv
        - apply_lve
      pool:
        name: MDV-ADO-AGENTS-01
      jobs:
        - job: scan
          steps:
            - task: AzureCLI@2
              displayName: Trigger Policy State Scan - Non Live
              inputs:
                scriptType: bash
                azureSubscription: 'ado_nonlive_workload_identity'
                scriptLocation: inlineScript
                inlineScript: |
                  az policy state scan --subscription 0511a7fe-771b-4ffa-9348-c59e9c4a87bd
                  az policy state scan --subscription 8cdb5405-7535-4349-92e9-f52bddc7833a
                  az policy state scan --subscription e6b5053b-4c38-4475-a835-a025aeb3d8c7
            - task: AzureCLI@2
              displayName: Trigger Policy State Scan - Live
              inputs:
                scriptType: bash
                azureSubscription: 'ado_live_workload_identity'
                scriptLocation: inlineScript
                inlineScript: |
                  az policy state scan --subscription e7819cdc-66af-4611-9dba-b9958e5b6d7d
                  az policy state scan --subscription 9ab65d81-930d-4cc0-a93d-367e14676bc0
